#!/bin/bash
curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
sudo yum install -y nodejs
sudo yum install -y java-11-amazon-corretto
sudo yum install -y gcc-c++ make
sudo yum install -y httpd
sudo npm install -g forever 
sudo npm install -g bower

# Set up the system variables and cron jobs
cd ~/fsdf-setup/tools
node prepare_account.js

# Get the apache configuration and turn on the HTTPD server
echo "Downloading "
cd ~
git clone https://github.com/Tomella/apache-configuration.git
bash apache-configuration/source/deploy
sudo chkconfig httpd on

# Let's get the Solr app running and loading the data
source $HOME/fsdf-setup/tools/gazetteer

# Load up placenames app.
cd ~
git clone https://github.com/Tomella/elvis-placenames.git
cd elvis-placenames
npm install
bower install
bash deployment/deploy-placenames

# Load up positioning app.
cd ~
git clone https://github.com/Tomella/elvis-positioning.git
cd elvis-positioning
npm install
bower install
bash code-deploy/static_deploy

# Load up elevation app.
cd ~
git clone https://github.com/Tomella/fsdf-elvis.git
cd fsdf-elvis
npm install
bower install
bash code-deploy/create_service

# Load up placenames upload app.
cd ~
git clone https://github.com/Tomella/elvis-upload.git
cd elvis-upload
npm install --only=prod
bower install
bash code-deploy/install_dependencies
cd ..